
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/lib/store";
import Head from 'next/head';
import { ThemeProvider } from "@/lib/features/ThemeContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
         <head>
      
<link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet" />
        <link rel="icon" href="/favicon.png" type="image/x-icon" />
      
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<ThemeProvider>
          {children}
        </ThemeProvider>
      
      </body>
    </html>
  );
}
